### ISSUE TITLE
8 packages have newer versions incompatible with dependency constraints

### ISSUE THREAD

**Issue by dandumit** [luis901101/honeywell_scanner#23]
Hello,
I am new to flutter. I am trying to run first command :
`flutter pub add honeywell_scanner`
and I get 
```
"honeywell_scanner" is already in "dependencies". Will try to update the constraint.
Resolving dependencies...
Downloading packages...
  collection 1.18.0 (1.19.0 available)
  leak_tracker 10.0.4 (10.0.5 available)
  leak_tracker_flutter_testing 3.0.3 (3.0.5 available)
  material_color_utilities 0.8.0 (0.12.0 available)
  meta 1.12.0 (1.15.0 available)
  string_scanner 1.2.0 (1.3.0 available)
  test_api 0.7.0 (0.7.3 available)
  vm_service 14.2.1 (14.2.4 available)
Got dependencies!
8 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
```

Any hint would be highly apreciated.
Thank you,
Daniel

**Comment by luis901101** [comment]
That is not any problem that is just a summary of pub get after adding a dependency, is common to have dependencies not pointing to latest version due to constraints, I recommend you to check https://docs.flutter.dev and also https://semver.org/.
I will close this issue as is not related to the plugin
