### ISSUE TITLE
BlackView 5100 Pro equipped with honeywell - not supported

### ISSUE THREAD

**Issue by andreribeiropinto104** [luis901101/honeywell_scanner#3]
Hi, I'm using BlackView 5100 Pro equipped with honeywell. I've run the example but it says the device is not supported. There is some modification that it is possible to implement to support this type of equipment?
Thanks in advance

**Comment by luis901101** [comment]
I don't see that device in the supported devices list from the official **DataCollection** library. AFAIK supported devices list shows only Honeywell PDA devices, the one you are using is a Blackview device which is not Honeywell manufactured... in that case the only thing to do should be to check if the Honeywell hardware equipped in this Blackview it is supported by the DataCollection library.

Officially the Honeywell DataCollection library does not offer a function to check if a device is supported, alternatively I implemented a feature to check this. What I do is basically to wait for `DecodeService` to bind, then service gets connected and `AidcManager` gets created and finally `onCreated` function gets called; then a bool property `supported` changes to true.

The "supported device" implementation of this plugin is trustworthy, but it is an asynchronously process, so until the service gets binded and AidcManager gets created the plugin will indicate the device is not supported...
In the example app the `isSupported()` checking is made in the `initState` which is too fast and maybe the `DecodeService` is not yet binded for the Honeywell equipment, I recommend you to just ignore the "unsupported device" message and wait a few seconds then try to scan any common barcode or qrcode to check if it works; if no code gets scanned then it's not supported.

Regarding the modification to support this equipment:
- If the problem were something at initialization or configuration level in the plugin itself then yes, it can be easily fixed. The thing here is that I don't have a device like the one you have to be able to do some tests.
- If the problem is related to the Honeywell `DataCollection` library I'm afraid there is nothing we can do, AFAIK this library is not open source, so the only thing would be to wait for an update that includes support for this specific equipment.

_I encourage you to download the source code of this plugin and debug your device initialization for you to check what happens on `DecodeService` binding._
