### ISSUE TITLE
> Project with path ':honeywell' could not be found in project ':honeywell_scanner'.

### ISSUE THREAD

**Issue by sanketwarule** [luis901101/honeywell_scanner#4]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Warules\flutter\.pub-cache\hosted\pub.dartlang.org\honeywell_scanner-3.1.4+12\android\build.gradle' line: 43

* What went wrong:
A problem occurred evaluating project ':honeywell_scanner'.
> Project with path ':honeywell' could not be found in project ':honeywell_scanner'.

**Comment by luis901101** [comment]
Did you followed the five steps described in the README? Specifically the **Second** and **Third** steps seems to be the ones related to your issue.

**Comment by sanketwarule** [comment]
Thank you, after trying second and third section in your Readme file I was able to run project successfully.
Actually I am also creating a plugin for zebra scanner, but I was facing same issue so I searched for the plugins who uses aar dependency and came across your plugin.

Is there any other solution so that end user don't need to manually add aar and do changes in manifest file?

**Comment by luis901101** [comment]
You're welcome.

- The changes in manifest file is only because a conflict with the `android:label` which is defined in the `honeywell.aar`. **.aar** packages should not define the `android:label` in its manifest this is something for apps not for packages, but as `honeywell.aar` defines it then you have to make the change in your app manifest. Anyway this change to the manifest is not always, it depends on the package dependency.
- Regarding to the manually importing of `.aar` package, this is because the honeywell sdk is not published in any repository like maven or github _(at least as far as I know)_, if it were published, then the `honeywell_scanner` plugin could define the depedency implementation and the package would be downloaded to the gradle/maven cache and be available for your app. As this is not the case, then the honeywell .aar package has to be added manually to the project which depends on it. Maybe there is a more easy/automatic way of adding the .aar dependency as a local dependency, but so far I only know the way I described on the README.

In your case, if the zebra scanner sdk is published as a package in some repository, then you would not have to worry about manual package handling.

**Comment by sanketwarule** [comment]
Thank you for coordination and quick reply
